import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ViewTransitions } from 'next-view-transitions';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export const metadata = {
  viewport:
    'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: '#f0f0f0' }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: '#ffffff' }}
      >
        <div
          className="fixed top-0 w-screen h-screen z-0 border-2 border-red-500"
          id="fullscreen"
        ></div>
        {children}
      </body>
    </html>
  );
}
